### ISSUE TITLE
I can't make it work with Nuxt 3

### ISSUE THREAD

**Issue by fermaud** [netlify/netlify-emails-plugin#131]
Hi, first thank you for your work.
I can't make **netlify-emails-plugin** works with nuxt 3... When it build, there is no /emails route function available. Have you tried it already ? 
If you need more details just ask me. (It works perfectly with nuxt 2)
best regards

**Comment by spraddles** [comment]
Same here, I'm having endless problems with Netlify + Nuxt 3.
I'm trying to use a serverless function for my contact form with SendGrid, but I'm getting these issues:

- can't access the preview link (I get `Function not found...`) so I can't see my email templates
- on deploy the build fails as Netlify requires `esbuild-linux-64` but my local machine (Macbook Pro Monterey) does not

I followed this guide exactly:
https://docs.netlify.com/netlify-labs/experimental-features/email-integration

**Comment by lemusthelroy** [comment]
Thanks for filing this issue.

We are currently doing quite a bit of work in the background to make this integration far more compatible with a range of frameworks. I will ensure Nuxt is in the list of frameworks we are testing in our latest update that will be coming very soon.

When the next update is released, I will check back in on this issue to make sure it is also resolved for you.

**Comment by fermaud** [comment]
@lemusthelroy thank you very much for your answer and your work 🙏🏼

**Comment by lemusthelroy** [comment]
Just so that you are aware, at the end of this week we will be removing this repository, as the codebase for this integration now lives elsewhere. We will be using Netlify forums to discuss the email integration and talking about any issues in the future. We are already tracking this issue internally at Netlify, however, if there is any further concern about the particular issue you have raised, we would encourage you to raise it in the forum which we will be actively monitoring.
