### ISSUE TITLE
"Function not found..." when using Netlify CLI local (npx) instead of global package

### ISSUE THREAD

**Issue by tjsheppard** [netlify/netlify-emails-plugin#133]
You get "Function not found..." (404) response in the browser if you use the local install of Netlify CLI instead of the global.
It would be cool if this could work with npx or at least add a comment on the docs that it must be the global install and use of Netlify CLI.

**Comment by lemusthelroy** [comment]
Just so that you are aware, at the end of this week we will be removing this repository, as the codebase for this integration now lives elsewhere. We will be using Netlify forums to discuss the email integration and talking about any issues in the future. We are already tracking this issue internally at Netlify, however, if there is any further concern about the particular issue you have raised, we would encourage you to raise it in the forum which we will be actively monitoring.
