### ISSUE TITLE
Add MailerSend as an email provider

### ISSUE THREAD

**Issue by Agathe-Brusset** [netlify/netlify-emails-plugin#134]
Hello to the Netlify team!
I'm Agathe Brusset, project manager of MailerSend, a solution to send transactional emails via API or SMTP. We would love to connect MailerSend to Netlify. Would you consider integrating our solution into your email plugin as an email provider?

Please find more details on our website: [www.mailersend.com](http://www.mailersend.com/)
Our API documentation: [www.developers.mailersend.com](http://www.developers.mailersend.com/)
Our SDKs:

- [PHP](https://github.com/mailersend/mailersend-php)
- [Laravel](https://github.com/mailersend/mailersend-laravel-driver)
- [NodeJS](https://github.com/mailersend/mailersend-nodejs)
- [Go](https://github.com/mailersend/mailersend-go)
- [Python](https://github.com/mailersend/mailersend-python)
- [Ruby](https://github.com/mailersend/mailersend-ruby)

Let us know when you create an account so we can approve you.

Regards,
Agathe Brusset

**Comment by wein-hillary** [comment]
Hey there @Agathe-Brusset 👋 

It's great to hear from you! 

I am a Technical Program Manager here at Netlify and would love to forward your inquiry over to our Partnerships team so that they can discuss a path forward for our two teams. Do you have an email address I can use to connect you with them? Thanks in advance!

**Comment by Agathe-Brusset** [comment]
Awesome, thank you! I sent you a DM on Linkedin instead :) 
Looking forward hearing from your team.

**Comment by lemusthelroy** [comment]
Just so that you are aware, at the end of this week we will be removing this repository, as the codebase for this integration now lives elsewhere. I can see that @wein-hillary has passed on your inquiry so I will close this issue ahead of us removing the repository.

Thanks again for getting in touch
